// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhUw9tA5h-xqRG0gryoGCVvD50OThPj-k',
    appId: '1:769769795661:web:8a420da3a9ad743ea8ec04',
    messagingSenderId: '769769795661',
    projectId: 'myapplication-b8cd5',
    authDomain: 'myapplication-b8cd5.firebaseapp.com',
    storageBucket: 'myapplication-b8cd5.firebasestorage.app',
    measurementId: 'G-DJK5P7JFMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbebMo_UT9e1EhaUrNHQWeQh_4qPmolIc',
    appId: '1:769769795661:android:3c282dd8345b41aca8ec04',
    messagingSenderId: '769769795661',
    projectId: 'myapplication-b8cd5',
    storageBucket: 'myapplication-b8cd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5MlVX2a-h7cuixyTNGrxtHNovRZ-I2js',
    appId: '1:769769795661:ios:4a4db2ac260929b6a8ec04',
    messagingSenderId: '769769795661',
    projectId: 'myapplication-b8cd5',
    storageBucket: 'myapplication-b8cd5.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );
}
