// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe-XFtjfFMqi6KJHykcczDrJxn1MBKR7A',
    appId: '1:821653807363:web:e0cfd76fdd9f152999c936',
    messagingSenderId: '821653807363',
    projectId: 'auth-c2150',
    authDomain: 'auth-c2150.firebaseapp.com',
    storageBucket: 'auth-c2150.firebasestorage.app',
    measurementId: 'G-RRG6K8L3EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdKvtRI3-GU81OMNNT_1ss6LvkwUO_534',
    appId: '1:821653807363:android:59ddb859d632b14b99c936',
    messagingSenderId: '821653807363',
    projectId: 'auth-c2150',
    storageBucket: 'auth-c2150.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-6_4WUcAFLfyJKFyvK8ozIf_uSP6C9YI',
    appId: '1:821653807363:ios:5b5e79ca465a0c6099c936',
    messagingSenderId: '821653807363',
    projectId: 'auth-c2150',
    storageBucket: 'auth-c2150.firebasestorage.app',
    iosBundleId: 'com.example.email',
  );
}
